### PR TITLE
Refactor to CLI, add automation, add ERC-1155 + OpenSea shared storefront

### PR DESCRIPTION
**Pull request by 0xechan**
First, I apologize for the massive PR :rofl:. I want to be clear that I'm open to changes, and I welcome your feedback. **Please feel free to take your time on this review.** I am not in a hurry to merge.

There are a few key changes I made here. 

##CLI
I added a CLI layer with the command `nftsnap`, removed `npm start`, and moved the variables from code to environment variables. See README for details on those changes. This has a couple impacts, including being able to run this on a server using something like a scheduled task with secure environment variables.

##Automation
This was a requirement for my purposes. I have too many collections to watch, so I added the ability to create JSON configuration that is automated using `nftsnap automate`. Again, see README.

##Reorganized project
Sorry about this one, this might be frustrating. The idea here is that I wanted to also have the option of using this as a library. So `index.js` simply exports the functions that my little app will want to use. Then `cli.js` is the entry point for the CLI. The rest was just house cleaning.

### CODE REVIEW

**Comment by zobront** [comment]
This looks amazing. I'm on the road so need a few days to get through it, but very excited to see the finished product and merge it in. Stay tuned.

**Comment by 0xechan** [comment]
No problem @zobront. I'm making some small changes as I build my back-end. Nothing major. No rush.

**Comment by zobront** [comment]
@etheria-chan Incredible work with this. Such an improvement. Merging this in now. Thank you!

**Comment by 0xechan** [comment]
> @etheria-chan Incredible work with this. Such an improvement. Merging this in now. Thank you!

Thank you! I considered converting to typescript, but didn't want to do this if it would be bothersome.

Have you considered serving this to npm?

**Pull request merged**
